/**
 * CATÁLOGO DE DESARROLLO — NO ES DATO DE PRODUCCIÓN.
 *
 * Sirve para construir y probar la tienda mientras no exista la base D1.
 * En la Etapa 3 este archivo se borra: `src/lib/catalogo.ts` pasa a leer de
 * D1 y el dueño carga sus productos reales desde la app de administración.
 *
 * Son productos de importación genéricos, sin marcas ni datos de nadie.
 */

import type { Categoria, Producto } from "./tipos";

export const CATEGORIAS_DESARROLLO: Categoria[] = [
  { id: 1, slug: "plantas-electricas", nombre: { es: "Plantas eléctricas", en: "Generators" }, emoji: "⚡", orden: 1, visible: true },
  { id: 2, slug: "motos", nombre: { es: "Motos", en: "Motorcycles" }, emoji: "🏍️", orden: 2, visible: true },
  { id: 3, slug: "bicicletas", nombre: { es: "Bicicletas", en: "Bicycles" }, emoji: "🚲", orden: 3, visible: true },
  { id: 4, slug: "carros", nombre: { es: "Carros", en: "Cars" }, emoji: "🚗", orden: 4, visible: true },
  { id: 5, slug: "herramientas", nombre: { es: "Herramientas", en: "Tools" }, emoji: "🔧", orden: 5, visible: true },
  { id: 6, slug: "repuestos", nombre: { es: "Repuestos", en: "Parts" }, emoji: "⚙️", orden: 6, visible: true },
];

export const PRODUCTOS_DESARROLLO: Producto[] = [
  {
    id: 1,
    slug: "planta-electrica-3-5-kw-portatil",
    categoriaSlug: "plantas-electricas",
    nombre: { es: "Planta eléctrica 3.5 kW portátil", en: "3.5 kW Portable Generator" },
    descripcion: {
      es: "Generador portátil de 3.5 kW ideal para casa, taller o finca. Motor a gasolina de 4 tiempos, arranque manual, tanque de 15 litros y hasta 11 horas de autonomía a media carga.",
      en: "3.5 kW portable generator for home, workshop or farm use. Four-stroke gasoline engine, recoil start, 15-liter tank and up to 11 hours of runtime at half load.",
    },
    precio: 640,
    precioAnterior: 790,
    costo: 410,
    stock: 12,
    sku: "PLE-035",
    publicado: true,
    destacado: true,
    etiqueta: { es: "Más vendido", en: "Best seller" },
    emoji: "⚡",
    fotos: [],
    variantes: [
      { id: 11, nombre: { es: "Arranque manual", en: "Recoil start" }, stock: 8, precioExtra: 0 },
      { id: 12, nombre: { es: "Arranque eléctrico", en: "Electric start" }, stock: 4, precioExtra: 90 },
    ],
    especificaciones: [
      { etiqueta: { es: "Potencia máxima", en: "Peak power" }, valor: { es: "3.5 kW", en: "3.5 kW" } },
      { etiqueta: { es: "Voltaje", en: "Voltage" }, valor: { es: "120 V / 240 V", en: "120 V / 240 V" } },
      { etiqueta: { es: "Tanque", en: "Fuel tank" }, valor: { es: "15 litros", en: "15 liters" } },
      { etiqueta: { es: "Autonomía", en: "Runtime" }, valor: { es: "11 horas", en: "11 hours" } },
      { etiqueta: { es: "Garantía", en: "Warranty" }, valor: { es: "12 meses", en: "12 months" } },
    ],
  },
  {
    id: 2,
    slug: "planta-electrica-5-kw-arranque-electrico",
    categoriaSlug: "plantas-electricas",
    nombre: { es: "Planta eléctrica 5 kW arranque eléctrico", en: "5 kW Electric Start Generator" },
    descripcion: {
      es: "Generador de 5 kW con arranque eléctrico y batería incluida. Pensado para negocios que no pueden quedarse sin luz: nevera, congelador, punto de pago y luces al tiempo.",
      en: "5 kW generator with electric start and battery included. Built for businesses that cannot afford an outage: refrigerator, freezer, point of sale and lighting at once.",
    },
    precio: 980,
    costo: 640,
    stock: 6,
    sku: "PLE-050",
    publicado: true,
    destacado: true,
    emoji: "⚡",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Potencia máxima", en: "Peak power" }, valor: { es: "5 kW", en: "5 kW" } },
      { etiqueta: { es: "Arranque", en: "Start" }, valor: { es: "Eléctrico con batería", en: "Electric with battery" } },
      { etiqueta: { es: "Tanque", en: "Fuel tank" }, valor: { es: "25 litros", en: "25 liters" } },
      { etiqueta: { es: "Garantía", en: "Warranty" }, valor: { es: "12 meses", en: "12 months" } },
    ],
  },
  {
    id: 3,
    slug: "planta-electrica-2-kw-inverter",
    categoriaSlug: "plantas-electricas",
    nombre: { es: "Planta eléctrica 2 kW inverter silenciosa", en: "2 kW Silent Inverter Generator" },
    descripcion: {
      es: "Generador inverter de 2 kW, silencioso y liviano. Entrega corriente estable para computadores, televisores y equipos sensibles.",
      en: "2 kW inverter generator, quiet and lightweight. Delivers clean power for computers, televisions and sensitive equipment.",
    },
    precio: 430,
    costo: 275,
    stock: 9,
    sku: "PLE-020",
    publicado: true,
    destacado: false,
    emoji: "⚡",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Potencia máxima", en: "Peak power" }, valor: { es: "2 kW", en: "2 kW" } },
      { etiqueta: { es: "Ruido", en: "Noise" }, valor: { es: "58 dB", en: "58 dB" } },
      { etiqueta: { es: "Peso", en: "Weight" }, valor: { es: "21 kg", en: "21 kg" } },
    ],
  },
  {
    id: 4,
    slug: "planta-electrica-8-kw-trifasica",
    categoriaSlug: "plantas-electricas",
    nombre: { es: "Planta eléctrica 8 kW trifásica", en: "8 kW Three-Phase Generator" },
    descripcion: {
      es: "Generador trifásico de 8 kW para taller o pequeña industria. Motor diésel refrigerado por aire y tablero de control con horómetro.",
      en: "8 kW three-phase generator for workshops or light industry. Air-cooled diesel engine and control panel with hour meter.",
    },
    precio: 2150,
    costo: 1490,
    stock: 3,
    sku: "PLE-080",
    publicado: true,
    destacado: false,
    etiqueta: { es: "Nuevo", en: "New" },
    emoji: "⚡",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Potencia máxima", en: "Peak power" }, valor: { es: "8 kW", en: "8 kW" } },
      { etiqueta: { es: "Combustible", en: "Fuel" }, valor: { es: "Diésel", en: "Diesel" } },
      { etiqueta: { es: "Fases", en: "Phases" }, valor: { es: "Trifásico", en: "Three-phase" } },
    ],
  },
  {
    id: 5,
    slug: "motocicleta-150cc-doble-proposito",
    categoriaSlug: "motos",
    nombre: { es: "Motocicleta 150cc doble propósito", en: "150cc Dual-Sport Motorcycle" },
    descripcion: {
      es: "Motocicleta 150cc doble propósito, lista para ciudad y trocha. Suspensión reforzada, frenos de disco delanteros y tablero digital.",
      en: "150cc dual-sport motorcycle, ready for city streets and rough roads. Reinforced suspension, front disc brakes and digital dashboard.",
    },
    precio: 1890,
    costo: 1240,
    stock: 4,
    sku: "MOT-150",
    publicado: true,
    destacado: true,
    emoji: "🏍️",
    fotos: [],
    variantes: [
      { id: 51, nombre: { es: "Rojo", en: "Red" }, stock: 2, precioExtra: 0 },
      { id: 52, nombre: { es: "Negro", en: "Black" }, stock: 2, precioExtra: 0 },
    ],
    especificaciones: [
      { etiqueta: { es: "Cilindraje", en: "Displacement" }, valor: { es: "150 cc", en: "150 cc" } },
      { etiqueta: { es: "Transmisión", en: "Transmission" }, valor: { es: "5 velocidades", en: "5-speed" } },
      { etiqueta: { es: "Frenos", en: "Brakes" }, valor: { es: "Disco / tambor", en: "Disc / drum" } },
      { etiqueta: { es: "Garantía", en: "Warranty" }, valor: { es: "12 meses", en: "12 months" } },
    ],
  },
  {
    id: 6,
    slug: "motocicleta-electrica-2000w",
    categoriaSlug: "motos",
    nombre: { es: "Motocicleta eléctrica 2000W", en: "2000W Electric Motorcycle" },
    descripcion: {
      es: "Moto eléctrica de 2000W con batería de litio extraíble. Hasta 80 km de recorrido por carga y cero gasto de combustible.",
      en: "2000W electric motorcycle with removable lithium battery. Up to 80 km per charge and zero fuel cost.",
    },
    precio: 1450,
    costo: 950,
    stock: 5,
    sku: "MOT-E20",
    publicado: true,
    destacado: false,
    emoji: "🛵",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Motor", en: "Motor" }, valor: { es: "2000 W", en: "2000 W" } },
      { etiqueta: { es: "Autonomía", en: "Range" }, valor: { es: "80 km", en: "80 km" } },
      { etiqueta: { es: "Batería", en: "Battery" }, valor: { es: "Litio extraíble", en: "Removable lithium" } },
    ],
  },
  {
    id: 7,
    slug: "bicicleta-electrica-500w",
    categoriaSlug: "bicicletas",
    nombre: { es: "Bicicleta eléctrica 500W", en: "500W Electric Bicycle" },
    descripcion: {
      es: "Bicicleta eléctrica de 500W con batería extraíble, cinco niveles de asistencia y frenos de disco. Marco de aluminio y llantas todo terreno.",
      en: "500W electric bicycle with removable battery, five assist levels and disc brakes. Aluminum frame and all-terrain tires.",
    },
    precio: 720,
    costo: 470,
    stock: 2,
    sku: "BIC-E50",
    publicado: true,
    destacado: true,
    etiqueta: { es: "Nuevo", en: "New" },
    emoji: "🚲",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Motor", en: "Motor" }, valor: { es: "500 W", en: "500 W" } },
      { etiqueta: { es: "Autonomía", en: "Range" }, valor: { es: "55 km", en: "55 km" } },
      { etiqueta: { es: "Marco", en: "Frame" }, valor: { es: "Aluminio", en: "Aluminum" } },
    ],
  },
  {
    id: 8,
    slug: "bicicleta-montanera-29",
    categoriaSlug: "bicicletas",
    nombre: { es: 'Bicicleta montañera 29"', en: '29" Mountain Bike' },
    descripcion: {
      es: 'Bicicleta montañera rin 29", 21 cambios y suspensión delantera. Buena relación precio-calidad para venta al por mayor.',
      en: '29" mountain bike with 21 speeds and front suspension. Strong value for wholesale.',
    },
    precio: 235,
    costo: 148,
    stock: 16,
    sku: "BIC-M29",
    publicado: true,
    destacado: false,
    emoji: "🚲",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Rin", en: "Wheel size" }, valor: { es: '29"', en: '29"' } },
      { etiqueta: { es: "Cambios", en: "Speeds" }, valor: { es: "21", en: "21" } },
    ],
  },
  {
    id: 9,
    slug: "carro-electrico-utilitario",
    categoriaSlug: "carros",
    nombre: { es: "Carro eléctrico utilitario", en: "Electric Utility Vehicle" },
    descripcion: {
      es: "Vehículo eléctrico utilitario de dos puestos con platón de carga. Ideal para fincas, conjuntos residenciales y bodegas.",
      en: "Two-seat electric utility vehicle with cargo bed. Ideal for farms, residential complexes and warehouses.",
    },
    precio: 6900,
    costo: 4850,
    stock: 2,
    sku: "CAR-EU2",
    publicado: true,
    destacado: false,
    emoji: "🚗",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Capacidad", en: "Capacity" }, valor: { es: "2 personas", en: "2 people" } },
      { etiqueta: { es: "Carga", en: "Payload" }, valor: { es: "500 kg", en: "500 kg" } },
      { etiqueta: { es: "Autonomía", en: "Range" }, valor: { es: "90 km", en: "90 km" } },
    ],
  },
  {
    id: 10,
    slug: "triciclo-de-carga-motorizado",
    categoriaSlug: "carros",
    nombre: { es: "Triciclo de carga motorizado", en: "Motorized Cargo Tricycle" },
    descripcion: {
      es: "Triciclo de carga con motor 200cc y platón volcable. Herramienta de trabajo para reparto, construcción y agricultura.",
      en: "Cargo tricycle with 200cc engine and dump bed. A work tool for delivery, construction and farming.",
    },
    precio: 2450,
    costo: 1690,
    stock: 3,
    sku: "CAR-T20",
    publicado: true,
    destacado: false,
    emoji: "🛺",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Cilindraje", en: "Displacement" }, valor: { es: "200 cc", en: "200 cc" } },
      { etiqueta: { es: "Carga", en: "Payload" }, valor: { es: "800 kg", en: "800 kg" } },
    ],
  },
  {
    id: 11,
    slug: "kit-de-herramientas-108-piezas",
    categoriaSlug: "herramientas",
    nombre: { es: "Kit de herramientas 108 piezas", en: "108-Piece Tool Kit" },
    descripcion: {
      es: "Juego de 108 piezas en estuche rígido: llaves, copas, destornilladores y accesorios en acero cromo vanadio.",
      en: "108-piece set in a hard case: wrenches, sockets, screwdrivers and accessories in chrome vanadium steel.",
    },
    precio: 110,
    costo: 62,
    stock: 38,
    sku: "HER-108",
    publicado: true,
    destacado: true,
    emoji: "🔧",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Piezas", en: "Pieces" }, valor: { es: "108", en: "108" } },
      { etiqueta: { es: "Material", en: "Material" }, valor: { es: "Cromo vanadio", en: "Chrome vanadium" } },
      { etiqueta: { es: "Estuche", en: "Case" }, valor: { es: "Rígido", en: "Hard case" } },
    ],
  },
  {
    id: 12,
    slug: "compresor-de-aire-50-litros",
    categoriaSlug: "herramientas",
    nombre: { es: "Compresor de aire 50 litros", en: "50-Liter Air Compressor" },
    descripcion: {
      es: "Compresor de aire de 50 litros y 2.5 HP con manómetro doble. Para taller, llantería o pintura.",
      en: "50-liter, 2.5 HP air compressor with dual gauge. For workshops, tire shops or painting.",
    },
    precio: 285,
    costo: 178,
    stock: 11,
    sku: "HER-C50",
    publicado: true,
    destacado: false,
    emoji: "🛠️",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Capacidad", en: "Tank" }, valor: { es: "50 litros", en: "50 liters" } },
      { etiqueta: { es: "Potencia", en: "Power" }, valor: { es: "2.5 HP", en: "2.5 HP" } },
    ],
  },
  {
    id: 13,
    slug: "soldadora-inverter-200a",
    categoriaSlug: "herramientas",
    nombre: { es: "Soldadora inverter 200A", en: "200A Inverter Welder" },
    descripcion: {
      es: "Soldadora inverter de 200 amperios, liviana y de arranque estable. Incluye careta, porta electrodo y cable de masa.",
      en: "200-amp inverter welder, lightweight with stable arc start. Includes helmet, electrode holder and ground cable.",
    },
    precio: 165,
    costo: 98,
    stock: 14,
    sku: "HER-S20",
    publicado: true,
    destacado: false,
    emoji: "⚙️",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Amperaje", en: "Amperage" }, valor: { es: "200 A", en: "200 A" } },
      { etiqueta: { es: "Voltaje", en: "Voltage" }, valor: { es: "110 V / 220 V", en: "110 V / 220 V" } },
    ],
  },
  {
    id: 14,
    slug: "bateria-de-litio-48v-20ah",
    categoriaSlug: "repuestos",
    nombre: { es: "Batería de litio 48V 20Ah", en: "48V 20Ah Lithium Battery" },
    descripcion: {
      es: "Batería de litio 48V 20Ah con BMS integrado y cargador. Compatible con bicicletas y motos eléctricas de 500W a 2000W.",
      en: "48V 20Ah lithium battery with built-in BMS and charger. Compatible with 500W to 2000W electric bicycles and motorcycles.",
    },
    precio: 295,
    costo: 185,
    stock: 19,
    sku: "REP-B48",
    publicado: true,
    destacado: true,
    emoji: "🔋",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Voltaje", en: "Voltage" }, valor: { es: "48 V", en: "48 V" } },
      { etiqueta: { es: "Capacidad", en: "Capacity" }, valor: { es: "20 Ah", en: "20 Ah" } },
      { etiqueta: { es: "Ciclos", en: "Cycles" }, valor: { es: "1000+", en: "1000+" } },
    ],
  },
  {
    id: 15,
    slug: "transferencia-automatica-63a",
    categoriaSlug: "repuestos",
    nombre: { es: "Transferencia automática 63A", en: "63A Automatic Transfer Switch" },
    descripcion: {
      es: "Interruptor de transferencia automática de 63A. Cuando se va la luz arranca la planta y la conecta sola.",
      en: "63A automatic transfer switch. When utility power fails it starts the generator and switches over automatically.",
    },
    precio: 310,
    costo: 198,
    stock: 11,
    sku: "REP-T63",
    publicado: true,
    destacado: false,
    emoji: "🔌",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Amperaje", en: "Amperage" }, valor: { es: "63 A", en: "63 A" } },
      { etiqueta: { es: "Fases", en: "Phases" }, valor: { es: "Monofásico", en: "Single-phase" } },
    ],
  },
  {
    id: 16,
    slug: "kit-de-mantenimiento-para-planta",
    categoriaSlug: "repuestos",
    nombre: { es: "Kit de mantenimiento para planta eléctrica", en: "Generator Maintenance Kit" },
    descripcion: {
      es: "Kit de mantenimiento con filtro de aire, filtro de aceite, bujía y empaques. Para el servicio de las 100 horas.",
      en: "Maintenance kit with air filter, oil filter, spark plug and gaskets. For the 100-hour service.",
    },
    precio: 45,
    costo: 24,
    stock: 24,
    sku: "REP-K01",
    publicado: true,
    destacado: false,
    emoji: "🧰",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Compatibilidad", en: "Fits" }, valor: { es: "Plantas 2 kW a 8 kW", en: "2 kW to 8 kW generators" } },
    ],
  },
  {
    id: 17,
    slug: "casco-certificado-para-moto",
    categoriaSlug: "repuestos",
    nombre: { es: "Casco certificado para moto", en: "Certified Motorcycle Helmet" },
    descripcion: {
      es: "Casco abatible con visor antirrayas y forro desmontable. Certificado y disponible en varias tallas.",
      en: "Modular helmet with anti-scratch visor and removable liner. Certified and available in several sizes.",
    },
    precio: 68,
    costo: 36,
    stock: 42,
    sku: "REP-C01",
    publicado: true,
    destacado: false,
    emoji: "🪖",
    fotos: [],
    variantes: [
      { id: 171, nombre: { es: "Talla M", en: "Size M" }, stock: 14, precioExtra: 0 },
      { id: 172, nombre: { es: "Talla L", en: "Size L" }, stock: 18, precioExtra: 0 },
      { id: 173, nombre: { es: "Talla XL", en: "Size XL" }, stock: 10, precioExtra: 0 },
    ],
    especificaciones: [
      { etiqueta: { es: "Tipo", en: "Type" }, valor: { es: "Abatible", en: "Modular" } },
      { etiqueta: { es: "Visor", en: "Visor" }, valor: { es: "Antirrayas", en: "Anti-scratch" } },
    ],
  },
  {
    id: 18,
    slug: "bomba-de-agua-2-pulgadas",
    categoriaSlug: "herramientas",
    nombre: { es: "Motobomba de agua 2 pulgadas", en: '2" Water Pump' },
    descripcion: {
      es: "Motobomba a gasolina de 2 pulgadas, 7 HP. Mueve hasta 30.000 litros por hora para riego o achique.",
      en: '2" gasoline water pump, 7 HP. Moves up to 30,000 liters per hour for irrigation or drainage.',
    },
    precio: 198,
    costo: 121,
    stock: 8,
    sku: "HER-B02",
    publicado: true,
    destacado: false,
    emoji: "💧",
    fotos: [],
    variantes: [],
    especificaciones: [
      { etiqueta: { es: "Succión", en: "Inlet" }, valor: { es: '2"', en: '2"' } },
      { etiqueta: { es: "Caudal", en: "Flow" }, valor: { es: "30.000 L/h", en: "30,000 L/h" } },
      { etiqueta: { es: "Potencia", en: "Power" }, valor: { es: "7 HP", en: "7 HP" } },
    ],
  },
];
